### ISSUE TITLE
Add documentation for vertical lines in plot

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/wikipediaviews#13]
e.g. see http://wikipediaviews.org/displayviewsformultiplemonths.php?tag=Pages%20created%20by%20Issa%20Rice%20in%202016&language=en&device=desktop&allmonths=allmonths

There are vertical blue and red lines in the plot, but no explanation of what they are. I would suggest explaining that they show the addition of mobile/spider pageviews and the API switch.

**Comment by vipulnaik** [comment]
Fixed (note that there is now only a vertical red line).
