### ISSUE TITLE
Publish plotting code

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/wikipediaviews#16]
The original version of the plotting code is at <https://gist.github.com/riceissa/8726e6a90d4a7634f3dd79cc1fdb63d5>. It would be good to do one or more of the following:

- Link to that Gist somewhere in the README and other relevant places.
- Include either the original source or modified source in the Wikipedia Views repository (in either case, noting whether it is modified or not). The original source is [essentially public domain](http://unlicense.org/) so either is possible.

**Comment by vipulnaik** [comment]
Done a while ago, forgot to close this
