### ISSUE TITLE
Look into automation of SQL insertion code generation from country breakdown pages

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/wikipediaviews#22]
Basically read from pages like https://stats.wikimedia.org/archive/squid_reports/2018-01/SquidReportPageViewsPerCountryBreakdownHuge.htm and output SQL like the one at https://github.com/vipulnaik/wikipediaviews/blob/master/sql/country-language-data.sql

**Comment by riceissa** [comment]
Work in progress: https://github.com/riceissa/wikipediaviews-country-breakdown (the basic scraping for each page is done, but I still need to loop through all the months and print the SQL).

I ran into some difficulties with strange-looking Wikipedia names, specifically "Other", "Portal", "m Wp", "Commons Wp", "wwwhttp Wp", "zero Wp", "plhttp Wp", "enhttp Wp", "eshttp Wp". Right now I'm just ignoring these, but maybe you'd like to do something else.

Am I correct to assume that December 2014 is the first time these reports became available? Also I think the reports stopped in September 2018.

**Comment by riceissa** [comment]
Ok, this is done now at https://github.com/riceissa/wikipediaviews-country-breakdown

You can find the output SQL at `out-2019-05-09.sql`.

Right now the year/month combinations are hard-coded so if the script is run in the future, that will need to be modified.

**Comment by vipulnaik** [comment]
@riceissa It looks like this is failing to insert, because it includes `zh-tw` as a language. However, there is no separate `zh-tw` Wikipedia; it redirects to `zh` Wikipedia.

The situation seems a bit complicated. It is explained here in some more detail: https://en.wikipedia.org/wiki/Chinese_Wikipedia#Automatic_conversion_between_traditional_and_simplified_Chinese_characters

My suggested approach: For countries that have `zh-tw`, add the `zh-tw` count into the `zh` count. Alternative ideas are also welcome. Also, can you check if there are any other languages with similar issues?

**Comment by riceissa** [comment]
Other similar languages:

* nb (see the Norway section [here](https://stats.wikimedia.org/archive/squid_reports/2014-12/SquidReportPageViewsPerCountryBreakdownHuge.htm)); probably this means Norwegian (Bokmål)
* There are lots of duplicate "be" rows, e.g. see [this page](https://stats.wikimedia.org/archive/squid_reports/2014-12/SquidReportPageViewsPerCountryBreakdownHuge.htm) and search for "Belarus". Notice how there are two rows called "Belarusian Wp". Maybe one of them is intended to refer to [be-tarask](https://en.wikipedia.org/wiki/Belarusian_Wikipedia).
* be-tarask
* xmf, e.g. see [this page](https://stats.wikimedia.org/archive/squid_reports/2014-12/SquidReportPageViewsPerCountryBreakdownHuge.htm) and search for "xmf Wp"; https://en.wikipedia.org/wiki/Mingrelian_language
* gag https://en.wikipedia.org/wiki/Gagauz_language
* ten, subdomain used for Wikipedia's tenth anniversary celebrations https://ten.wikipedia.org/wiki/Main_Page

**Comment by riceissa** [comment]
I've made code changes over at https://github.com/riceissa/wikipediaviews-country-breakdown to make it easy to combine view counts for different languages, so now I just need a list of languages that should be combined.

**Comment by riceissa** [comment]
I wrote a small script to compare the list of Wikipedias on [Wikipedia Views](https://github.com/vipulnaik/wikipediaviews/blob/13aadcaec2e5e2b6fdf4a728a6360bec735f692d/sql/language-insertions.sql) with the one at [Wikimedia meta-wiki](https://meta.wikimedia.org/w/index.php?title=List_of_Wikipedias&oldid=19016835): https://gist.github.com/riceissa/1b633cf2cf0629e0e87f715c828326a3

The output of the script is:

* Things in meta not in Vipul {'sat', 'pfl', 'din', 'gor', 'olo', 'xmf', 'inh', 'atj', 'lrc', 'jam', 'shn', 'gag', 'kbp', 'be-tarask', 'azb', 'lfn', 'dty', 'hyw', 'ady', 'tcy'}
* Things in Vipul not in meta {'mo'}

"mo: has been redirected to ro:, as of December 2017" https://meta.wikimedia.org/wiki/List_of_Wikipedias
